# This is part of WHY2
# Copyright (C) 2022 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

variables:
  CLIENT: "./out/why2-chat-client"
  SERVER: "./out/why2-chat-server"
  CORE_OUTPUT: "./out/why2-core-test"
  CORE_APP: "why2"
  VALGRIND: "valgrind --leak-check=full --show-leak-kinds=reachable --track-origins=yes -s"

why2-chat-build:
  stage: build
  image: rust:latest # Fixes cargo installation problems in ./configure.sh
  script:
    - apt update # Update repos
    - apt install sudo lsb-release -y # Install needed stuff
    - chmod +x configure.sh # Permissions
    - sudo ./configure.sh # Preparation
    - make install BYPASS_CHECK=true # Install WHY2
    - make build_chat # Build Chat
  artifacts:
    paths:
      - $CLIENT
      - $SERVER

why2-core-test:
  stage: build
  image: rust:latest
  script:
    - apt update # Update repos
    - apt install sudo lsb-release valgrind -y # Install needed stuff
    - chmod +x configure.sh # Permissions
    - sudo ./configure.sh # Preparation
    - make install BYPASS_CHECK=true # Install WHY2
    - make test_core # Build WHY2 Test
    - ./$CORE_OUTPUT # Test Lib
    - $APP # Test App
    - $VALGRIND $APP # Test Lib by Valgrind