# This is part of WHY2
# Copyright (C) 2022-2025 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

image: rust:latest

stages:
  - test
  - build
  - aur

# Test WHY2
test-why2:
  stage: test
  image: rust:latest
  only:
    - development
  script:
    - echo "Test WHY2"
    - cargo test --all --verbose --features legacy --release

# Build chat for linux
build-why2-chat-linux:
  stage: build
  only:
    - development
  needs:
    - job: test-why2
  script:
    - echo "Build WHY2 Chat for Linux"
    - cargo build --features client --release
    - cargo build --bin why2-server --features server --release
  artifacts:
    name: "why2-chat-linux"
    paths:
      - ./target/release/why2
      - ./target/release/why2-server

# Upload to Arch Linux User Repository
upload-to-aur:
  stage: aur
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && $CI_SERVER_URL == "https://git.satan.red"'
      when: always
    - when: never
  script:
    # Install dependencies
    - apt update && apt install -y git grep sed

    # Setup SSH
    - mkdir -p ~/.ssh
    - echo "$AUR_SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo -e "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> ~/.ssh/known_hosts
    - echo -e "Host aur.archlinux.org\n\tUser aur\n\tIdentityFile ~/.ssh/id_ed25519" > ~/.ssh/config

    # Setup Git
    - git config --global user.name "Expandera"
    - git config --global user.email "gitlab@satan.red"

    # Extract version
    - VERSION=$(grep '^version =' Cargo.toml | head -n1 | sed -E 's/version\s*=\s*"(.*)"/\1/')

    # Clone & modify AUR repository
    - git clone ssh://aur@aur.archlinux.org/why2.git
    - cd why2

    # Update PKGBUILD
    - sed -i "s/^pkgver=.*/pkgver=$VERSION/" PKGBUILD
    - sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

    # Update .SRCINFO
    - sed -i "s/^\s*pkgver = .*/\tpkgver = $VERSION/" .SRCINFO
    - sed -i "s/^\s*pkgrel = .*/\tpkgrel = 1/" .SRCINFO

    # Commit & push
    - git add PKGBUILD .SRCINFO
    - git commit -m "update version to $VERSION" -m "(automated upload)"
    - git push
