# This is part of WHY2
# Copyright (C) 2022-2025 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

image: rust:latest

stages:
  - test
  - build
  - aur

# Test core
test-why2-core:
  stage: test
  image: rust:latest
  only:
    - development
  script:
    - echo "Test WHY2 Core"
    - cargo test --all --verbose

# Build chat for linux
build-why2-chat-linux:
  stage: build
  only:
    - development
  needs:
    - job: test-why2-core
  script:
    - echo "Build WHY2 Chat for Linux"
    - cargo build --features client --release
    - cargo build --features server --release
  artifacts:
    name: "why2-chat-linux"
    paths:
      - ./target/release/why2
      - ./target/release/why2-server

# Upload to Arch Linux User Repository
upload-to-aur:
  stage: aur
  image: archlinux:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "development" && $CI_SERVER_URL == "https://git.satan.red"'
      when: always
    - when: never
  script:
    - pacman -Syu --no-confirm && pacman -S base-devel git grep sed
    - mkdir -p ~/.ssh
    - echo "$AUR_SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keygen -y -f ~/.ssh/id_ed25519 > /dev/null || (echo "Invalid SSH key" && exit 1)
    - echo -e "Host aur.archlinux.org\n\tStrictHostKeyChecking no\n\tUser aur\n\tIdentityFile ~/.ssh/id_ed25519" > ~/.ssh/config
    - VERSION=$(grep '^version =' Cargo.toml | sed -E 's/version = "(.*)-rex"/\1/')
    - git clone ssh://aur@aur.archlinux.org/why2.git aur-repo
    - cd aur-repo
    - sed -i "s/^pkgver=.*/pkgver=$VERSION/" PKGBUILD
    - makepkg --printsrcinfo > .SRCINFO
    - git add PKGBUILD .SRCINFO
    - git commit -m "update version to $VERSION" -m "(automated upload)"
    - git push
