# This is part of WHY2
# Copyright (C) 2022-2025 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[workspace]
resolver = "2"
members = [
    "core",
    "chat",
    "tests",
]

[workspace.package]
version = "0.3.0-rex"
authors = ["Václav Šmejkal <engo@satan.red>"]
edition = "2024"
license = "GPL-3.0-only"
repository = "https://git.satan.red/ENGO150/WHY2"
description = "Lightweight, fast, secure, and easy to use encryption system."
keywords = ["encryption", "chat", "security", "rust"]
categories = ["cryptography", "network-programming", "command-line-utilities"]

[workspace.dependencies]
rand = "0.9.2"
rand_chacha = "0.9.0"
sha2 = "0.10.9"
serde = "1.0.228"
serde_json = "1.0.145"
