# This is part of WHY2
# Copyright (C) 2022-2026 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Network
default_port = 1204 # Server port
socks5_enabled = false # Use SOCKS5 proxying (changing requires restart)
socks5_addr = "127.0.0.1:9150" # Local proxy address

# Auto-connect
auto_connect = false # Automatic connection to 'auto_connect_addr'
auto_connect_addr = "0.0.0.0" # See 'auto_connect'

# Colors
disable_colors = false # Disable message colors
username_color = "none" # Color of username (change via command)
message_color = "none" # Color of message (change via command)

# Other
show_id = false # Show client IDs in chat
