# This is part of WHY2
# Copyright (C) 2022-2026 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Network
server_ip = "0.0.0.0" # Server address
server_port = 1204 # Server port

# Voice Chat
enable_voice_chat = true # Enable (changing requires restart)

# Appearance
server_name = "WHY2 Server" # Name of the server
server_username = "server" # Username server will use

# Cleanup
communication_time = 300 # Seconds waiting for client message before stopping communication (+- 5 seconds)

# Restrictions
allow_register = true # Allow new users to register
check_client_version = true # Allow only clients with same version as server
max_clients = 20 # Maximal number of clients connected at the same time
max_upload_size = 50 # Maximal size (MB) of file uploads

# Auth
max_auth_tries = 3 # Times asking client for username/registration password (a valid, long enough password)
min_password_length = 12 # Minimal password length
max_username_length = 20 # Maximal username length
min_username_length = 4 # Minimal username length

# Spam
spam_protection = true # Spam protection
max_packet_size = 2000000 # Maximal packet size (2MB)
max_message_length = 256 # Maximal text message length
min_message_delay = 750 # Minimal ms delay between user messages (to prevent spamming)
max_message_delay_violations = 3 # Maximal 'spam' messages that can be sent without getting disconnected

# Channel
max_channel_length = 20 # Maximal length of channel name
