# This is part of WHY2
# Copyright (C) 2022-2026 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[package]
name = "why2-chat"
version = "1.5.3"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Lightweight, fast and secure chat application powered by WHY2 encryption."
keywords = ["encryption", "security", "cryptography", "network", "chat"]
categories = ["cryptography", "network-programming"]
readme = "./README.md"

default-run = "why2"

[lib]
doc = false

[[bin]]
name = "why2"
path = "src/bin/client/mod.rs"
required-features = ["client_base"]
doc = false

[[bin]]
name = "why2-server"
path = "src/bin/server.rs"
required-features = ["server"]
doc = false

[dependencies]
# GLOBAL
why2 = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }
serde_json = { version = "1.0.150", optional = true }
wincode = { version = "0.5.5", features = ["derive"], optional = true }
dirs = { version = "6.0.0", optional = true }
p521 = { version = "0.13.3", features = ["ecdh", "pkcs8"], optional = true }
ml-kem = { version = "0.3.2", features = ["getrandom"], optional = true }
ureq = { version = "3.3.0", optional = true }
semver = { version = "1.0.28", optional = true }
toml_edit = { version = "0.25.12", optional = true }
hkdf = { version = "0.13.0", optional = true }
socks = { version = "0.3.4", optional = true }
dashmap = { version = "6.2.1", optional = true }
rand = { version = "0.10.2", optional = true }

# CHAT (CLIENT SPECIFIC)
crossterm = { version = "0.29.0", optional = true }
colored = { version = "3.1.1", optional = true }

# VOICE CHAT (CLIENT)
cpal = { version = "0.18.1", optional = true, features = ["pulseaudio"] }
ringbuf = { version = "0.5.0", optional = true }
audiopus = { version = "0.2.0", optional = true }
gag = { version = "1.0.0", optional = true }
nnnoiseless = { version = "0.5.2", default-features = false, optional = true }
lewton = { version = "0.10.2", optional = true }

# SCREEN SHARE (CLIENT SPECIFIC)
crossbeam-channel = { version = "0.5.16", optional = true }
winit = { version = "0.30.13", optional = true }
xcap = { version = "0.9.6", default-features = false, optional = true }
pixels = { version = "0.17.1", optional = true }
openh264 = { version = "0.9.3", optional = true }

# CHAT (SERVER SPECIFIC)
argon2 = { version = "0.5.3", optional = true }
ctrlc = { version = "3.5.2", optional = true }
log = { version = "0.4.33", optional = true }
simple_logger = { version = "5.2.0", optional = true }

[features]
default = ["client"]

chat = [
    "dep:serde_json",
    "dep:wincode",
    "dep:ureq",
    "dep:toml_edit",
    "dep:dirs",
    "dep:semver",
    "dep:p521",
    "dep:ml-kem",
    "dep:hkdf",
    "dep:dashmap",
    "dep:rand",
]

client_base = [
    "chat",
    "dep:socks",
    "dep:crossterm",
    "dep:colored",
]

client_voice = [
    "dep:cpal",
    "dep:ringbuf",
    "dep:audiopus",
    "dep:gag",
    "dep:nnnoiseless",
    "dep:lewton",
]

client_screen = [
    "client_voice",
    "dep:crossbeam-channel",
    "dep:winit",
    "dep:libwayshot",
    "dep:xcap",
    "dep:pixels",
    "dep:openh264",
]

client = [
    "client_base",
    "client_voice",
    "client_screen",
]

server = [
    "chat",
    "dep:ctrlc",
    "dep:argon2",
    "dep:log",
    "dep:simple_logger",
]

[target.'cfg(target_os = "linux")'.dependencies]
libwayshot = { version = "0.8.0", default-features = false, optional = true }
