/*
This is part of WHY2
Copyright (C) 2022-2026 Václav Šmejkal

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/// Diffusion matrix for a grid of height 4.
///
/// Generated by the row `[1, 2, 4, 6]` as $M_{i,j} = m_{i \oplus j}$ — see [`MDS_8`], which is
/// the same construction at the default height and carries the full rationale.
pub const MDS_4: [[u64; 4]; 4] =
[
    [1, 2, 4, 6],
    [2, 1, 6, 4],
    [4, 6, 1, 2],
    [6, 4, 2, 1],
];

/// Diffusion matrix for a grid of height 8, the default.
///
/// # Shape
/// The matrix is **Hadamard**: $M_{i,j} = m_{i \oplus j}$, so the row below is the whole of it
/// and the matrix product is an XOR-convolution.
///
/// # Coefficients
/// Every entry is a sum of powers of $x$ with exponents below four, so multiplying by one is a
/// short chain of "shift up by one and fold the carry" steps and an XOR — the diffusion layer
/// needs no general field multiply and no carry-less multiply instruction at all.
///
/// The previous matrix was a Cauchy matrix whose entries were arbitrary 64-bit field elements.
/// It was just as MDS, but every one of its products was a real field multiplication, which is
/// why the old layer needed a carry-less multiply, four dispatched CPU backends and a Karatsuba
/// split to be affordable. The measured effect of the swap, at the default 8×8 grid: on a CPU
/// with `VPCLMULQDQ` the layer is about 1.3x faster, and on a target without any carry-less
/// multiply — where the old code fell back to a bitwise multiply — it is about **190x** faster.
///
/// # Involution
/// $M^2 = I$, so **this matrix is its own inverse** and the diffusion layer is as cheap to undo
/// as it is to apply. A Hadamard matrix squares to $(\bigoplus_k m_k)^2 I$, so this is exactly
/// the condition that the row XORs to one; [`is_involutory`](crate::grid) checks it at compile
/// time.
///
/// # How it was chosen
/// Of all vectors over $\mathbb{F}_{2^{64}}$ whose entries are below 16, this is the
/// lexicographically smallest one that both generates an MDS matrix and XORs to one, among those
/// of minimal total Hamming weight (13). Both properties were verified exhaustively: all 12869
/// square submatrices are non-singular, so the branch number is the maximal $H + 1 = 9$. There is
/// no cheaper one, and nothing was hand-picked out of a larger set.
pub const MDS_8: [[u64; 8]; 8] =
[
    [ 1,  2,  3,  8,  4, 10,  9, 14],
    [ 2,  1,  8,  3, 10,  4, 14,  9],
    [ 3,  8,  1,  2,  9, 14,  4, 10],
    [ 8,  3,  2,  1, 14,  9, 10,  4],
    [ 4, 10,  9, 14,  1,  2,  3,  8],
    [10,  4, 14,  9,  2,  1,  8,  3],
    [ 9, 14,  4, 10,  3,  8,  1,  2],
    [14,  9, 10,  4,  8,  3,  2,  1],
];

/// Diffusion matrix for a grid of height 16.
///
/// Same construction as [`MDS_8`]: Hadamard, involutory, and built from coefficients that are
/// sums of powers of $x$ — here with exponents below eight rather than below four, which is the
/// price of the larger order. All 601080389 square submatrices are non-singular, so the branch
/// number is the maximal $H + 1 = 17$.
///
/// # How it was chosen
/// The top-left quarter of a Hadamard matrix of order 16 is itself a Hadamard matrix of order 8,
/// and a submatrix of an MDS matrix is non-singular, so the first eight coefficients have to
/// generate an order-8 MDS matrix on their own. This row's first half is the lexicographically
/// smallest vector that does so at minimal weight over coefficients below 256; the second half
/// is the smallest completion found that leaves the whole order-16 matrix MDS and XORing to one.
/// Unlike [`MDS_4`] and [`MDS_8`] no claim of global minimality is made for it — the order-16
/// search space was not exhausted — only that the matrix has the properties above, each verified
/// rather than assumed.
pub const MDS_16: [[u64; 16]; 16] =
[
    [  1,   2,   3,   8,   4,  32,  64,  16,   5, 128,   6,  18,  12,  65, 132,  37],
    [  2,   1,   8,   3,  32,   4,  16,  64, 128,   5,  18,   6,  65,  12,  37, 132],
    [  3,   8,   1,   2,  64,  16,   4,  32,   6,  18,   5, 128, 132,  37,  12,  65],
    [  8,   3,   2,   1,  16,  64,  32,   4,  18,   6, 128,   5,  37, 132,  65,  12],
    [  4,  32,  64,  16,   1,   2,   3,   8,  12,  65, 132,  37,   5, 128,   6,  18],
    [ 32,   4,  16,  64,   2,   1,   8,   3,  65,  12,  37, 132, 128,   5,  18,   6],
    [ 64,  16,   4,  32,   3,   8,   1,   2, 132,  37,  12,  65,   6,  18,   5, 128],
    [ 16,  64,  32,   4,   8,   3,   2,   1,  37, 132,  65,  12,  18,   6, 128,   5],
    [  5, 128,   6,  18,  12,  65, 132,  37,   1,   2,   3,   8,   4,  32,  64,  16],
    [128,   5,  18,   6,  65,  12,  37, 132,   2,   1,   8,   3,  32,   4,  16,  64],
    [  6,  18,   5, 128, 132,  37,  12,  65,   3,   8,   1,   2,  64,  16,   4,  32],
    [ 18,   6, 128,   5,  37, 132,  65,  12,   8,   3,   2,   1,  16,  64,  32,   4],
    [ 12,  65, 132,  37,   5, 128,   6,  18,   4,  32,  64,  16,   1,   2,   3,   8],
    [ 65,  12,  37, 132, 128,   5,  18,   6,  32,   4,  16,  64,   2,   1,   8,   3],
    [132,  37,  12,  65,   6,  18,   5, 128,  64,  16,   4,  32,   3,   8,   1,   2],
    [ 37, 132,  65,  12,  18,   6, 128,   5,  16,  64,  32,   4,   8,   3,   2,   1],
];
