#ifndef WHY2_ENCRYPTER_H
#define WHY2_ENCRYPTER_H

char *encryptText(char *text, char *keyNew); //TEXT from WILL BE ENCRYPTED WITH RANDOM PASSWORD [KEY] (WHICH WILL BE PRINTED OUT) AND RETURNED

#endif