# This is part of WHY2
# Copyright (C) 2022-2026 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Build WHY2

on:
  push:
    branches: [ development ]

permissions:
  contents: read
  actions: read

jobs:
  build-why2-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Examples
        run: cargo build --examples --release -p why2 --verbose

  build-why2-chat:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev libopus-dev libpipewire-0.3-dev libegl-dev clang libclang-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew update && brew install opus pkg-config

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Client
        run: cargo build --release

      - name: Build Server
        run: cargo build --bin why2-server --no-default-features --features server --release

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: why2-chat-${{ matrix.os }}
          path: |
            ./target/release/why2${{ runner.os == 'Windows' && '.exe' || '' }}
            ./target/release/why2-server${{ runner.os == 'Windows' && '.exe' || '' }}
