# This is part of WHY2
# Copyright (C) 2022-2026 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Publish WHY2 to crates.io

on:
  push:
    branches: [ release ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v5
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth

    - run: cargo publish -p why2
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev libopus-dev libpipewire-0.3-dev

    - name: Wait for index update
      run: sleep 30

    - run: cargo publish -p why2-chat
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
