# This is part of WHY2
# Copyright (C) 2022-2025 Václav Šmejkal

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Test WHY2

on:
  push:
    branches: [ development ]
  workflow_dispatch:
  schedule:
    - cron: '40 22 12 4 2'

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  test-why2-encryption:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Test
        run: cargo test encrypt_decrypt --verbose --release -- --nocapture

  test-why2-grid-overflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Test
        run: cargo test verify_multi_grid_overflow --verbose --release -- --nocapture

  test-why2-diffusion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Input Diffusion Test
        run: cargo test test_input_diffusion --verbose --release -- --nocapture

      - name: Run Key Diffusion Test
        run: cargo test test_key_diffusion --verbose --release -- --nocapture

  test-why2-legacy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Test
        run: cargo test legacy_encrypt_decrypt --features legacy --verbose --release -- --nocapture
